import { useCallback, useEffect, useState } from "react";
import { AdminLayout } from "@/components/layout/AdminLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api";
import { toast } from "@/hooks/use-toast";
import { Activity, AlertTriangle, BarChart3, CheckCircle, CreditCard, Loader2, MessageSquare, RefreshCw, Search, Server, Users, Wallet } from "lucide-react";

type AnyRecord = Record<string, any>;
interface Overview { users:AnyRecord;campaigns:AnyRecord;messages:AnyRecord;wallets:AnyRecord;payments:AnyRecord;recent_customers:AnyRecord[] }
interface Service { service_name:string;instance_id:string|null;last_seen_at:string;age_seconds:number;healthy:boolean;metadata?:AnyRecord }
interface Provider { provider:string;available:boolean;credits:number|null;low:boolean|null;threshold:number;error?:string;checked_at?:string }
interface Paged<T> { pagination:{page:number;per_page:number;total:number;last_page:number};customers?:T[];campaigns?:T[] }

const number=(value:any)=>Number(value||0).toLocaleString();
const money=(value:any)=>`R${Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=(value:any)=>value?new Date(String(value).replace(' ','T')).toLocaleString():'—';
const badgeVariant=(state:string)=>state==='delivered'||state==='completed'||state==='ready'?'default':state==='failed'||state==='partially_failed'?'destructive':'secondary';
const payload=<T,>(response:any):T=>(response?.data??response) as T;

function Metric({title,value,detail,icon:Icon}:{title:string;value:string;detail:string;icon:any}){
  return <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">{title}</CardTitle><Icon className="h-4 w-4 text-muted-foreground"/></CardHeader><CardContent><div className="text-2xl font-bold">{value}</div><p className="text-xs text-muted-foreground mt-1">{detail}</p></CardContent></Card>;
}

export default function AdminOperations(){
  const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);
  const [overview,setOverview]=useState<Overview|null>(null);const [services,setServices]=useState<Service[]>([]);const [provider,setProvider]=useState<Provider|null>(null);const [finance,setFinance]=useState<AnyRecord|null>(null);
  const [customers,setCustomers]=useState<AnyRecord[]>([]);const [campaigns,setCampaigns]=useState<AnyRecord[]>([]);const [customerSearch,setCustomerSearch]=useState('');const [campaignSearch,setCampaignSearch]=useState('');
  const [selectedCustomer,setSelectedCustomer]=useState<AnyRecord|null>(null);const [selectedCampaign,setSelectedCampaign]=useState<AnyRecord|null>(null);const [detailLoading,setDetailLoading]=useState(false);

  const load=useCallback(async(silent=false)=>{
    silent?setRefreshing(true):setLoading(true);
    const requests=[api.get<Overview>('/admin/operations/overview'),api.get<{services:Service[]}>('/admin/operations/services'),api.get<Provider>('/admin/operations/provider'),api.get<Paged<AnyRecord>>(`/admin/operations/customers?per_page=100&search=${encodeURIComponent(customerSearch)}`),api.get<Paged<AnyRecord>>(`/admin/operations/campaigns?per_page=100&search=${encodeURIComponent(campaignSearch)}`),api.get<AnyRecord>('/admin/operations/finance')];
    const results=await Promise.allSettled(requests);let failures=0;
    if(results[0].status==='fulfilled')setOverview(payload<Overview>(results[0].value));else failures++;
    if(results[1].status==='fulfilled')setServices((payload<{services:Service[]}>(results[1].value).services||[]).filter((service):service is Service=>Boolean(service&&service.service_name)));else failures++;
    if(results[2].status==='fulfilled')setProvider(payload<Provider>(results[2].value));else failures++;
    if(results[3].status==='fulfilled')setCustomers(payload<Paged<AnyRecord>>(results[3].value).customers||[]);else failures++;
    if(results[4].status==='fulfilled')setCampaigns(payload<Paged<AnyRecord>>(results[4].value).campaigns||[]);else failures++;
    if(results[5].status==='fulfilled')setFinance(payload<AnyRecord>(results[5].value));else failures++;
    if(failures)toast({title:'Partial admin data',description:`${failures} section${failures===1?'':'s'} could not be refreshed. Other sections remain available.`,variant:'destructive'});
    setLoading(false);setRefreshing(false);
  },[customerSearch,campaignSearch]);
  useEffect(()=>{load();},[load]);

  const openCustomer=async(id:number)=>{setDetailLoading(true);setSelectedCustomer({});try{const res=await api.get<AnyRecord>(`/admin/operations/customers/${id}`);setSelectedCustomer(payload<AnyRecord>(res));}catch(e:any){setSelectedCustomer(null);toast({title:'Customer unavailable',description:e.message,variant:'destructive'});}finally{setDetailLoading(false);}};
  const openCampaign=async(id:number)=>{setDetailLoading(true);setSelectedCampaign({});try{const res=await api.get<AnyRecord>(`/admin/operations/campaigns/${id}?per_page=100`);setSelectedCampaign(payload<AnyRecord>(res));}catch(e:any){setSelectedCampaign(null);toast({title:'Campaign unavailable',description:e.message,variant:'destructive'});}finally{setDetailLoading(false);}};

  if(loading)return <AdminLayout title="Platform Operations" subtitle="Canonical customer, messaging and financial operations"><div className="flex h-72 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin"/></div></AdminLayout>;
  const deliveryRate=Number(overview?.messages?.sent||0)+Number(overview?.messages?.delivered||0)>0?100*Number(overview?.messages?.delivered||0)/(Number(overview?.messages?.sent||0)+Number(overview?.messages?.delivered||0)):0;
  return <AdminLayout title="Platform Operations" subtitle="Live customer, messaging, wallet and provider activity" actions={<Button variant="outline" onClick={()=>load(true)} disabled={refreshing}><RefreshCw className={`mr-2 h-4 w-4 ${refreshing?'animate-spin':''}`}/>Refresh</Button>}>
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <Metric title="Customers" value={number(overview?.users?.total)} detail={`${number(overview?.users?.active)} active · ${number(overview?.users?.verified)} verified`} icon={Users}/>
        <Metric title="SMS campaigns" value={number(overview?.campaigns?.total)} detail={`${number(overview?.campaigns?.active)} active · ${number(overview?.campaigns?.scheduled)} scheduled`} icon={MessageSquare}/>
        <Metric title="Messages" value={number(overview?.messages?.total)} detail={`${deliveryRate.toFixed(1)}% delivered among sent`} icon={BarChart3}/>
        <Metric title="Payments received" value={money(overview?.payments?.received)} detail={`${number(overview?.payments?.completed)} completed payments`} icon={CreditCard}/>
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><Server className="h-5 w-5"/>Production services</CardTitle><CardDescription>Heartbeats from the actual cron and worker processes</CardDescription></CardHeader><CardContent className="space-y-3">{services.map(s=><div key={s.service_name} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{s.service_name}</p><p className="text-xs text-muted-foreground">Last seen {date(s.last_seen_at)} · {s.age_seconds}s ago</p></div><Badge variant={s.healthy?'default':'destructive'}>{s.healthy?'Healthy':'Stale'}</Badge></div>)}</CardContent></Card>
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5"/>LogicSMS provider</CardTitle><CardDescription>Upstream credits are separate from customer wallet credits</CardDescription></CardHeader><CardContent>{provider?.available?<div className="space-y-3"><div className="text-3xl font-bold">{number(provider.credits)} credits</div><Badge variant={provider.low?'destructive':'default'}>{provider.low?'Low provider balance':'Provider balance healthy'}</Badge><p className="text-sm text-muted-foreground">Alert threshold: {number(provider.threshold)} credits · checked {date(provider.checked_at)}</p></div>:<div className="flex gap-3 rounded-lg border border-destructive/30 p-4"><AlertTriangle className="h-5 w-5 text-destructive"/><div><p className="font-medium">Provider balance unavailable</p><p className="text-sm text-muted-foreground">{provider?.error||'The provider did not return a usable balance.'}</p></div></div>}</CardContent></Card>
      </div>
      <Tabs defaultValue="customers" className="space-y-4"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="customers">Customers</TabsTrigger><TabsTrigger value="campaigns">Campaigns</TabsTrigger><TabsTrigger value="finance">Finance</TabsTrigger></TabsList>
        <TabsContent value="customers"><Card><CardHeader><CardTitle>Customer mirror</CardTitle><CardDescription>Wallets, contacts, templates, opt-outs and messaging activity</CardDescription><div className="flex gap-2 pt-2"><Input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="Search name or email"/><Button variant="outline" onClick={()=>load(true)}><Search className="h-4 w-4"/></Button></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Status</TableHead><TableHead>Available</TableHead><TableHead>Reserved</TableHead><TableHead>Contacts</TableHead><TableHead>Campaigns</TableHead><TableHead>Messages</TableHead></TableRow></TableHeader><TableBody>{customers.map(c=><TableRow key={c.id} className="cursor-pointer" onClick={()=>openCustomer(c.id)}><TableCell><div className="font-medium">{c.name}</div><div className="text-xs text-muted-foreground">{c.email}</div></TableCell><TableCell><Badge variant={Number(c.is_active)?'default':'secondary'}>{Number(c.is_active)?'Active':'Inactive'}</Badge></TableCell><TableCell>{money(c.balance)}</TableCell><TableCell>{money(c.reserved)}</TableCell><TableCell>{number(c.contacts)}</TableCell><TableCell>{number(c.campaigns)}</TableCell><TableCell>{number(c.messages)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
        <TabsContent value="campaigns"><Card><CardHeader><CardTitle>Global SMS campaigns</CardTitle><CardDescription>Canonical queue, delivery and cost state for every customer</CardDescription><div className="flex gap-2 pt-2"><Input value={campaignSearch} onChange={e=>setCampaignSearch(e.target.value)} placeholder="Search campaign, customer or email"/><Button variant="outline" onClick={()=>load(true)}><Search className="h-4 w-4"/></Button></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Campaign</TableHead><TableHead>Customer</TableHead><TableHead>Status</TableHead><TableHead>Recipients</TableHead><TableHead>Delivered</TableHead><TableHead>Failed</TableHead><TableHead>Cost</TableHead></TableRow></TableHeader><TableBody>{campaigns.map(c=><TableRow key={c.id} className="cursor-pointer" onClick={()=>openCampaign(c.id)}><TableCell><div className="font-medium">{c.name}</div><div className="text-xs text-muted-foreground">{date(c.created_at)}</div></TableCell><TableCell><div>{c.user_name}</div><div className="text-xs text-muted-foreground">{c.user_email}</div></TableCell><TableCell><Badge variant={badgeVariant(c.state)}>{c.state}</Badge></TableCell><TableCell>{number(c.recipient_count)}</TableCell><TableCell>{number(c.delivered_count)}</TableCell><TableCell>{number(c.failed_count)}</TableCell><TableCell>{money(c.actual_cost)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
        <TabsContent value="finance"><div className="space-y-4"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric title="Cash received" value={money(finance?.payments?.received)} detail={`${number(finance?.payments?.total)} payment attempts`} icon={CreditCard}/><Metric title="Wallet liability" value={money(finance?.wallets?.balance)} detail={`${money(finance?.wallets?.reserved)} reserved`} icon={Wallet}/><Metric title="Credits issued" value={money(finance?.ledger?.credits_issued)} detail={`${number(finance?.ledger?.entries)} ledger entries`} icon={CheckCircle}/><Metric title="Credits consumed" value={money(finance?.ledger?.credits_debited)} detail="Canonical wallet debits" icon={MessageSquare}/></div><Card><CardHeader><CardTitle>Recent payments</CardTitle><CardDescription>Money received is reported separately from wallet credits</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Reference</TableHead><TableHead>Gateway</TableHead><TableHead>Status</TableHead><TableHead>Amount</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{(finance?.recent_payments||[]).map((p:AnyRecord)=><TableRow key={p.id}><TableCell><div>{p.user_name}</div><div className="text-xs text-muted-foreground">{p.user_email}</div></TableCell><TableCell>{p.merchant_reference}</TableCell><TableCell>{p.gateway}</TableCell><TableCell><Badge variant={badgeVariant(p.status)}>{p.status}</Badge></TableCell><TableCell>{money(p.amount)}</TableCell><TableCell>{date(p.created_at)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div></TabsContent>
      </Tabs>
    </div>
    <Dialog open={selectedCustomer!==null} onOpenChange={open=>!open&&setSelectedCustomer(null)}><DialogContent className="max-w-5xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Customer account mirror</DialogTitle><DialogDescription>Customer-visible resources and recent financial activity</DialogDescription></DialogHeader>{detailLoading?<Loader2 className="mx-auto my-12 h-8 w-8 animate-spin"/>:selectedCustomer?.customer&&<div className="space-y-5"><div className="grid gap-3 md:grid-cols-3"><Metric title={selectedCustomer.customer.name} value={money(selectedCustomer.customer.balance)} detail={`${selectedCustomer.customer.email} · ${money(selectedCustomer.customer.reserved)} reserved`} icon={Wallet}/><Metric title="Campaigns" value={number(selectedCustomer.counts.campaigns)} detail={`${number(selectedCustomer.counts.messages)} messages`} icon={MessageSquare}/><Metric title="Address book" value={number(selectedCustomer.counts.contacts)} detail={`${number(selectedCustomer.counts.contact_groups)} groups · ${number(selectedCustomer.counts.opt_outs)} opt-outs`} icon={Users}/></div><h3 className="font-semibold">Recent campaigns</h3><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Status</TableHead><TableHead>Recipients</TableHead><TableHead>Delivered</TableHead><TableHead>Cost</TableHead></TableRow></TableHeader><TableBody>{selectedCustomer.campaigns.map((c:AnyRecord)=><TableRow key={c.id}><TableCell>{c.name}</TableCell><TableCell><Badge variant={badgeVariant(c.state)}>{c.state}</Badge></TableCell><TableCell>{c.recipient_count}</TableCell><TableCell>{c.delivered_count}</TableCell><TableCell>{money(c.actual_cost)}</TableCell></TableRow>)}</TableBody></Table><h3 className="font-semibold">Recent payments</h3><Table><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Status</TableHead><TableHead>Amount</TableHead><TableHead>Date</TableHead></TableRow></TableHeader><TableBody>{selectedCustomer.payments.map((p:AnyRecord)=><TableRow key={p.id}><TableCell>{p.merchant_reference}</TableCell><TableCell><Badge variant={badgeVariant(p.status)}>{p.status}</Badge></TableCell><TableCell>{money(p.amount)}</TableCell><TableCell>{date(p.created_at)}</TableCell></TableRow>)}</TableBody></Table></div>}</DialogContent></Dialog>
    <Dialog open={selectedCampaign!==null} onOpenChange={open=>!open&&setSelectedCampaign(null)}><DialogContent className="max-w-6xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Campaign delivery detail</DialogTitle><DialogDescription>Per-recipient provider and delivery information</DialogDescription></DialogHeader>{detailLoading?<Loader2 className="mx-auto my-12 h-8 w-8 animate-spin"/>:selectedCampaign?.campaign&&<div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><h3 className="text-lg font-semibold">{selectedCampaign.campaign.name}</h3><Badge variant={badgeVariant(selectedCampaign.campaign.state)}>{selectedCampaign.campaign.state}</Badge><span className="text-sm text-muted-foreground">{selectedCampaign.campaign.user_name} · {selectedCampaign.campaign.user_email}</span></div><Table><TableHeader><TableRow><TableHead>Destination</TableHead><TableHead>Status</TableHead><TableHead>Segments</TableHead><TableHead>Provider reference</TableHead><TableHead>Attempts</TableHead><TableHead>Updated</TableHead><TableHead>Error</TableHead></TableRow></TableHeader><TableBody>{selectedCampaign.messages.map((m:AnyRecord)=><TableRow key={m.id}><TableCell>{m.destination}</TableCell><TableCell><Badge variant={badgeVariant(m.state)}>{m.state}</Badge></TableCell><TableCell>{m.segment_count}</TableCell><TableCell className="max-w-40 truncate">{m.provider_message_id||'—'}</TableCell><TableCell>{m.attempt_count}</TableCell><TableCell>{date(m.delivered_at||m.failed_at||m.sent_at||m.created_at)}</TableCell><TableCell className="max-w-64 truncate text-destructive">{m.last_error||'—'}</TableCell></TableRow>)}</TableBody></Table></div>}</DialogContent></Dialog>
  </AdminLayout>;
}
