import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { api, cancelSmsCampaign, exportCampaignMessages, getSmsCampaign, queueSmsCampaign, retrySmsCampaign } from "@/lib/api";
import { toast } from "@/hooks/use-toast";

interface Campaign { id:string;name:string;content:string;state:string;recipient_count:number;queued_count:number;processing_count:number;sent_count:number;delivered_count:number;failed_count:number;skipped_count:number;total_segments:number;estimated_cost:number;actual_cost:number;created_at:string;scheduled_at?:string;started_at?:string;completed_at?:string }
interface Message { id:string;destination:string;state:string;segment_count:number;actual_charge:number;sent_at?:string;delivered_at?:string;failed_at?:string;last_error?:string;contact_name?:string;contact_surname?:string;contact_email?:string }
const displayState=(state:string)=>state==='sent'?'Awaiting DLR':state==='retry'?'Retry scheduled':state.replace(/_/g,' ');

export default function CampaignDetails(){
 const {id=""}=useParams();const [campaign,setCampaign]=useState<Campaign|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [retrying,setRetrying]=useState(false);const [stateFilter,setStateFilter]=useState("all");
 const load=useCallback(async(showLoading=true)=>{if(showLoading)setLoading(true);try{const params:Record<string,string>={page:String(page),per_page:"50"};if(stateFilter!=="all")params.state=stateFilter;const [c,m]=await Promise.all([getSmsCampaign(id),api.get<{messages:Message[];meta:{total:number}}>(`/sms/campaigns-v2/${id}/messages`,params)]);const cr=c as typeof c&{campaign?:Campaign};const mr=m as typeof m&{messages?:Message[];meta?:{total?:number}};setCampaign(cr.campaign??(c.data?.campaign as Campaign));setMessages(mr.messages??m.data?.messages??[]);setTotal(Number(mr.meta?.total??m.data?.meta?.total??0))}catch(e){toast({title:"Unable to load campaign",description:e instanceof Error?e.message:"Please retry",variant:"destructive"})}finally{if(showLoading)setLoading(false)}},[id,page,stateFilter]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(false),30000);return()=>window.clearInterval(timer)},[load]);
 if(loading&&!campaign)return <DashboardLayout title="Campaign" subtitle="Loading…"><p>Loading campaign…</p></DashboardLayout>;
 if(!campaign)return <DashboardLayout title="Campaign not found" subtitle=""><Link to="/sms-campaigns">Back to campaigns</Link></DashboardLayout>;
 const canRetry=campaign.failed_count>0||messages.some(m=>m.state==='failed'||m.state==='retry');
 const retry=async()=>{setRetrying(true);try{const r=await retrySmsCampaign(id);toast({title:"Campaign retry queued",description:`${Number(r.retried_messages??r.data?.retried_messages??0)} message(s) will be retried. Delivered recipients were not added again.`});await load()}catch(e){toast({title:"Campaign could not be retried",description:e instanceof Error?e.message:"Please try again.",variant:"destructive"})}finally{setRetrying(false)}};
 const draft=async(action:'queue'|'cancel')=>{setRetrying(true);try{if(action==='queue')await queueSmsCampaign(id);else await cancelSmsCampaign(id);await load()}catch(e){toast({title:"Campaign could not be updated",description:e instanceof Error?e.message:"Please try again.",variant:"destructive"})}finally{setRetrying(false)}};
 const metrics=[["Recipients",campaign.recipient_count],["Pending dispatch",campaign.queued_count],["Processing",campaign.processing_count],["Awaiting DLR",Math.max(0,campaign.sent_count-campaign.delivered_count)],["Delivered",campaign.delivered_count],["Failed / undelivered",campaign.failed_count],["Skipped",campaign.skipped_count],["Segments",campaign.total_segments]];
 return <DashboardLayout title={campaign.name} subtitle={`Campaign: ${campaign.state==='completed'?'dispatch complete':displayState(campaign.state)}`} actions={<div className="flex flex-wrap gap-2">{campaign.state==='draft'&&<><Button onClick={()=>void draft('queue')} disabled={retrying}>Queue campaign</Button><Button variant="destructive" onClick={()=>void draft('cancel')} disabled={retrying}>Cancel draft</Button></>}{canRetry&&<Button onClick={()=>void retry()} disabled={retrying}>{retrying?"Retrying…":"Retry failed messages"}</Button>}<Button variant="outline" onClick={()=>void load()}>Refresh</Button><Button variant="outline" onClick={()=>void exportCampaignMessages(id,"sms")}>Export CSV</Button></div>}>
  <Link className="text-sm text-primary" to="/sms-campaigns">← Back to campaigns</Link>
  <div className="mt-5 grid grid-cols-2 gap-4 md:grid-cols-4">{metrics.map(([label,value])=><div key={String(label)} className="rounded-xl border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></div>)}</div>
  <div className="mt-6 rounded-xl border bg-card p-5"><p className="whitespace-pre-wrap">{campaign.content}</p><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><p>Estimated: R{Number(campaign.estimated_cost).toFixed(2)}</p><p>Actual: R{Number(campaign.actual_cost).toFixed(2)}</p><p>Created: {campaign.created_at}</p><p>Scheduled: {campaign.scheduled_at||"—"}</p><p>Started: {campaign.started_at||"—"}</p><p>Dispatch completed: {campaign.completed_at||"—"}</p></div></div>
  <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Recipient delivery details</h2><p className="text-sm text-muted-foreground">See which contact or manually entered number received each message.</p></div><Select value={stateFilter} onValueChange={v=>{setPage(1);setStateFilter(v)}}><SelectTrigger className="w-52"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All delivery states</SelectItem><SelectItem value="delivered">Delivered</SelectItem><SelectItem value="sent">Awaiting DLR</SelectItem><SelectItem value="failed">Failed / undelivered</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="processing">Processing</SelectItem><SelectItem value="retry">Retry scheduled</SelectItem><SelectItem value="skipped">Skipped</SelectItem></SelectContent></Select></div>
  <div className="mt-3 overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b bg-muted/50"><th className="p-3 text-left">Contact</th><th className="p-3 text-left">Destination</th><th className="p-3 text-left">Delivery state</th><th className="p-3">Segments</th><th className="p-3 text-left">Sent</th><th className="p-3 text-left">Delivered / failed</th><th className="p-3 text-left">Details</th></tr></thead><tbody>{messages.map(m=>{const contact=[m.contact_name,m.contact_surname].filter(Boolean).join(" ");return <tr key={m.id} className="border-b"><td className="p-3"><div className="font-medium">{contact||"Unsaved recipient"}</div>{m.contact_email&&<div className="text-xs text-muted-foreground">{m.contact_email}</div>}</td><td className="p-3">{m.destination}</td><td className="p-3 capitalize">{displayState(m.state)}</td><td className="p-3 text-center">{m.segment_count}</td><td className="p-3">{m.sent_at||"—"}</td><td className="p-3">{m.delivered_at||m.failed_at||"—"}</td><td className="p-3">{m.last_error||"—"}</td></tr>})}</tbody></table></div>
  <div className="mt-4 flex items-center justify-between"><p className="text-sm text-muted-foreground">Showing {messages.length} of {total}</p><div className="flex gap-2"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button variant="outline" disabled={page*50>=total} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div>
 </DashboardLayout>
}
